add_library(pch INTERFACE)

target_precompile_headers(pch INTERFACE
    <glbinding/gl/gl.h>
    <glbinding/gl/enum.h>
    <glbinding/gl/functions.h>
    <glbinding/gl/types.h>
    <fmt/core.h>
    <fmt/format.h>
    <fmt/std.h>
    <glm/glm.hpp>
    <glm/ext.hpp>
    <glm/gtc/type_ptr.hpp>
    <entt/entt.hpp>
    <entt/entity/registry.hpp>
    <entt/entity/handle.hpp>
    <entt/entity/entity.hpp>
    <entt/entity/component.hpp>
    <range/v3/all.hpp>
    <boost/any/basic_any.hpp>
    <boost/any/unique_any.hpp>
    <boost/container/small_vector.hpp>
    <boost/container/static_vector.hpp>
    <boost/unordered/unordered_flat_map.hpp>
    <boost/unordered/unordered_flat_set.hpp>
    <boost/uuid/uuid.hpp>
    <boost/uuid/uuid_hash.hpp>
    <boost/uuid/uuid_io.hpp>
    <boost/interprocess/mapped_region.hpp>
    <boost/interprocess/file_mapping.hpp>
    <boost/container_hash/hash.hpp>
    <boost/scope/scope_exit.hpp>
    <algorithm>
    <ranges>
    <iterator>
    <functional>
    <exception>
    <stdexcept>
    <memory>
    <utility>
    <compare>
    <typeinfo>
    <typeindex>
    <concepts>
    <type_traits>
    <chrono>
    <filesystem>
    <variant>
    <optional>
    <tuple>
    <fstream>
    <streambuf>
    <ios>
    <coroutine>
    <condition_variable>
    <thread>
    <atomic>
    <mutex>
    <shared_mutex>
    <stop_token>
    <queue>
    <map>
    <set>
    <string>
    <string_view>
    <vector>
    <span>
    <array>
    <list>
    <unordered_map>
)
